import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  introSidebar: [
    'intro',
  ],
  serverSidebar: [
    {
      type: 'category',
      label: 'Laravel Server',
      collapsed: false,
      items: [
        'laravel/getting-started',
        'laravel/models',
        'laravel/validation',
        'laravel/querying',
        'laravel/computed-attributes',
        'laravel/request-lifecycle',
        'laravel/policies',
        'laravel/route-groups',
        'laravel/nested-operations',
        'laravel/soft-deletes',
        'laravel/multi-tenancy',
        'laravel/custom-controllers',
        'laravel/audit-trail',
        'laravel/generator',
        'laravel/blueprint',
        'laravel/export-types',
      ],
    },
    {
      type: 'category',
      label: 'Best Practices',
      collapsed: true,
      link: {type: 'doc', id: 'laravel/best-practices/index'},
      items: [
        'laravel/best-practices/models-and-queries',
        'laravel/best-practices/authorization',
        'laravel/best-practices/tenant-safety',
        'laravel/best-practices/data-lifecycle',
        'laravel/best-practices/codegen',
      ],
    },
    'laravel/release-notes',
  ],
  railsSidebar: [
    {
      type: 'category',
      label: 'Rails Server',
      collapsed: false,
      items: [
        'rails/getting-started',
        'rails/models',
        'rails/validation',
        'rails/querying',
        'rails/computed-attributes',
        'rails/request-lifecycle',
        'rails/policies',
        'rails/route-groups',
        'rails/nested-operations',
        'rails/soft-deletes',
        'rails/multi-tenancy',
        'rails/custom-controllers',
        'rails/audit-trail',
        'rails/generator',
        'rails/blueprint',
        'rails/export-types',
      ],
    },
    'rails/release-notes',
  ],
  nestjsSidebar: [
    {
      type: 'category',
      label: 'NestJS Server',
      collapsed: false,
      items: [
        'nestjs/getting-started',
        'nestjs/models',
        'nestjs/validation',
        'nestjs/querying',
        'nestjs/computed-attributes',
        'nestjs/request-lifecycle',
        'nestjs/policies',
        'nestjs/route-groups',
        'nestjs/nested-operations',
        'nestjs/soft-deletes',
        'nestjs/multi-tenancy',
        'nestjs/custom-controllers',
        'nestjs/audit-trail',
        'nestjs/invitations',
        'nestjs/postman-export',
        'nestjs/generator',
        'nestjs/blueprint',
        'nestjs/export-types',
      ],
    },
    'nestjs/release-notes',
  ],
  reactSidebar: [
    {
      type: 'category',
      label: 'React Client',
      collapsed: false,
      items: [
        'react/getting-started',
        'react/authentication',
        'react/crud-hooks',
        'react/querying',
        'react/soft-deletes',
        'react/nested-operations',
        'react/invitations',
        'react/utilities',
        'react/typescript',
        'react/desktop-electron',
      ],
    },
  ],
};

export default sidebars;
